export const tours = [
  {
    id: "fts-001",
    title: "Giza Pyramids, Sphinx & Saqqara Day Tour (with Egyptologist)",
    slug: "giza-pyramids-sphinx-saqqara-day-tour",
    location: "Cairo",
    category: "Historical",
    duration: { label: "8 hours", hours: 8, days: 0 },
    rating: 4.8,
    reviewsCount: 1284,
    price: 45,
    oldPrice: 59,
    badges: ["Best Seller", "Free Cancellation", "Instant Confirmation"],
    image: "assets/images/cairo.svg",
    gallery: ["assets/images/cairo.svg", "assets/images/giza.svg", "assets/images/desert.svg"],
    shortDescription: "A classic Cairo highlight day with iconic viewpoints and flexible pacing.",
    fullDescription:
      "Explore the last remaining wonder of the ancient world with a licensed Egyptologist. Enjoy curated stops at the Giza Plateau, the Sphinx, and the Step Pyramid complex at Saqqara. This experience is designed for comfort, clear storytelling, and great photo opportunities.",
    highlights: [
      "Guided visit to the Giza Plateau and panoramic viewpoint",
      "Learn the hidden details behind the Sphinx and temple complex",
      "Discover Saqqara’s Step Pyramid and early tomb architecture",
      "Plenty of time for photos, local insights, and optional add-ons",
    ],
    included: ["Hotel pickup & drop-off", "Licensed Egyptologist guide", "Air-conditioned transport"],
    excluded: ["Entry tickets (pay on site)", "Lunch and drinks", "Gratuities"],
    itinerary: [
      { title: "Pickup in Cairo/Giza", description: "Meet your guide and start with a quick route briefing." },
      { title: "Giza Plateau", description: "Great Pyramid area, viewpoints, and Sphinx complex." },
      { title: "Saqqara", description: "Step Pyramid and selected tombs (depending on availability)." },
      { title: "Return", description: "Drop-off at your hotel or preferred central location." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: true,
  },
  {
    id: "fts-002",
    title: "Cairo Food & Bazaar Walk: Khan El Khalili Like a Local",
    slug: "cairo-food-bazaar-khan-el-khalili",
    location: "Cairo",
    category: "Culture & Food",
    duration: { label: "3.5 hours", hours: 3.5, days: 0 },
    rating: 4.7,
    reviewsCount: 642,
    price: 29,
    badges: ["Top Rated", "Small Group", "Free Cancellation"],
    image: "assets/images/bazaar.svg",
    gallery: ["assets/images/bazaar.svg", "assets/images/cairo.svg", "assets/images/nights.svg"],
    shortDescription: "Street food tastings, iconic alleys, and shopping tips without tourist traps.",
    fullDescription:
      "Taste your way through Cairo with a friendly local guide. Walk historic streets, try classic bites, learn what (and how) to bargain, and end with a cozy tea stop. Perfect for first-time visitors who want a safe, fun intro to the city.",
    highlights: [
      "Guided walk through Khan El Khalili’s most photogenic lanes",
      "Curated tastings of popular Egyptian street foods",
      "Bargaining tips and authentic craft recommendations",
      "A relaxed finish with tea in a classic café setting",
    ],
    included: ["Guide", "Food tastings", "Tea stop"],
    excluded: ["Hotel pickup", "Extra purchases", "Gratuities"],
    itinerary: [
      { title: "Meet-up", description: "Quick intro and route overview." },
      { title: "Bazaar walk", description: "Historic lanes, shops, and storytelling stops." },
      { title: "Tastings", description: "Seasonal bites selected for freshness and safety." },
      { title: "Tea stop", description: "Unwind and get local recommendations." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
  {
    id: "fts-003",
    title: "Luxor West Bank: Valley of the Kings + Hatshepsut Temple",
    slug: "luxor-west-bank-valley-of-the-kings-hatshepsut",
    location: "Luxor",
    category: "Historical",
    duration: { label: "6 hours", hours: 6, days: 0 },
    rating: 4.9,
    reviewsCount: 987,
    price: 55,
    oldPrice: 69,
    badges: ["Top Rated", "Free Cancellation", "Instant Confirmation"],
    image: "assets/images/luxor.svg",
    gallery: ["assets/images/luxor.svg", "assets/images/temple.svg", "assets/images/nile.svg"],
    shortDescription: "Iconic tombs, a legendary female pharaoh, and expert storytelling.",
    fullDescription:
      "Spend a focused morning on Luxor’s West Bank with a route built for less waiting and more meaning. Your guide helps you navigate the tomb tickets strategy and the best times for key viewpoints.",
    highlights: [
      "Valley of the Kings tomb visits with context you’ll remember",
      "Hatshepsut’s terraced temple and photo stops",
      "Comfortable transport and efficient routing",
      "Option to add extra tombs depending on time and availability",
    ],
    included: ["Pickup & drop-off (Luxor)", "Guide", "Transport"],
    excluded: ["Entry tickets", "Lunch", "Gratuities"],
    itinerary: [
      { title: "Pickup", description: "Start early for cooler weather and fewer crowds." },
      { title: "Valley of the Kings", description: "Select tombs, history, and Q&A." },
      { title: "Hatshepsut Temple", description: "Guided visit and photo time." },
      { title: "Return", description: "Drop-off in Luxor." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Private",
    featured: true,
  },
  {
    id: "fts-004",
    title: "Aswan Nubian Village Experience (Boat Ride + Culture Stop)",
    slug: "aswan-nubian-village-boat-ride-experience",
    location: "Aswan",
    category: "Culture & Food",
    duration: { label: "4 hours", hours: 4, days: 0 },
    rating: 4.6,
    reviewsCount: 412,
    price: 33,
    badges: ["Family Friendly", "Free Cancellation"],
    image: "assets/images/aswan.svg",
    gallery: ["assets/images/aswan.svg", "assets/images/nile.svg", "assets/images/village.svg"],
    shortDescription: "A relaxed, colorful intro to Nubian culture with scenic river views.",
    fullDescription:
      "Sail along the Nile to a vibrant Nubian village. Learn about local traditions, enjoy a welcoming culture stop, and take photos of iconic painted homes. Ideal for travelers who want an easy, authentic afternoon.",
    highlights: [
      "Traditional boat ride with Nile scenery",
      "Nubian cultural stop with friendly hosts",
      "Great photo opportunities and relaxed pacing",
      "Local recommendations for Aswan evenings",
    ],
    included: ["Boat ride", "Guide/host support"],
    excluded: ["Pickup (optional add-on)", "Food and drinks", "Gratuities"],
    itinerary: [
      { title: "Meet-up", description: "Start near the river with quick safety briefing." },
      { title: "Boat ride", description: "Scenic ride along the Nile islands." },
      { title: "Village visit", description: "Cultural stop and free time for photos." },
      { title: "Return", description: "Back to the starting point." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
  {
    id: "fts-005",
    title: "Hurghada Snorkeling Cruise: Reefs + Island Stop (Lunch Included)",
    slug: "hurghada-snorkeling-cruise-reefs-island-lunch",
    location: "Hurghada",
    category: "Sea & Snorkeling",
    duration: { label: "8 hours", hours: 8, days: 0 },
    rating: 4.5,
    reviewsCount: 2214,
    price: 39,
    oldPrice: 49,
    badges: ["Best Seller", "Lunch Included", "Free Cancellation"],
    image: "assets/images/hurghada.svg",
    gallery: ["assets/images/hurghada.svg", "assets/images/reef.svg", "assets/images/island.svg"],
    shortDescription: "Two snorkel stops, clear water, and a chilled island break in the Red Sea.",
    fullDescription:
      "Cruise to vibrant reef sites selected by the crew for conditions on the day. Enjoy two guided snorkel sessions, lunch on board, and an island stop for swimming and photos.",
    highlights: [
      "Two guided snorkel stops at reef sites",
      "Lunch onboard with soft drinks",
      "Island stop for beach time",
      "Beginner-friendly with safety briefing",
    ],
    included: ["Boat cruise", "Snorkel gear", "Lunch", "Soft drinks"],
    excluded: ["Hotel transfers (optional)", "Gratuities", "Diving add-ons"],
    itinerary: [
      { title: "Boarding", description: "Safety briefing and gear fitting." },
      { title: "Reef stop 1", description: "Guided snorkeling session." },
      { title: "Lunch", description: "Fresh lunch served onboard." },
      { title: "Reef stop 2 + Island", description: "Second snorkel stop, then island free time." },
      { title: "Return", description: "Back to the marina." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: true,
  },
  {
    id: "fts-006",
    title: "Sharm El Sheikh Desert Safari: Quad Bike + Bedouin Tea",
    slug: "sharm-desert-safari-quad-bedouin-tea",
    location: "Sharm El Sheikh",
    category: "Adventure",
    duration: { label: "4.5 hours", hours: 4.5, days: 0 },
    rating: 4.4,
    reviewsCount: 1180,
    price: 27,
    badges: ["Popular", "Free Cancellation"],
    image: "assets/images/sharm.svg",
    gallery: ["assets/images/sharm.svg", "assets/images/desert.svg", "assets/images/camp.svg"],
    shortDescription: "A fun desert ride with a cultural pause—perfect for late afternoon plans.",
    fullDescription:
      "Kick up the sand on a guided quad route with wide-open views. Stop for Bedouin tea and learn the basics of desert life. Designed for both first-timers and riders who want an easy, safe route.",
    highlights: [
      "Guided quad route with safety-first pacing",
      "Bedouin tea stop and cultural intro",
      "Photo stops at scenic points",
      "Optional upgrades available on-site",
    ],
    included: ["Guide", "Quad bike briefing", "Bedouin tea stop"],
    excluded: ["Hotel transfers (optional)", "Scarf/goggles", "Gratuities"],
    itinerary: [
      { title: "Meet-up", description: "Briefing, helmet, and controls practice." },
      { title: "Desert ride", description: "Guided ride with stops and viewpoints." },
      { title: "Bedouin stop", description: "Tea and cultural chat." },
      { title: "Return", description: "Back to starting point." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
  {
    id: "fts-007",
    title: "2-Day Nile Highlights: Luxor to Aswan (Temples + Scenic Stops)",
    slug: "2-day-nile-highlights-luxor-to-aswan",
    location: "Luxor",
    category: "Multi-day",
    duration: { label: "2 days", hours: 0, days: 2 },
    rating: 4.7,
    reviewsCount: 356,
    price: 210,
    badges: ["New", "Free Cancellation", "Instant Confirmation"],
    image: "assets/images/nile.svg",
    gallery: ["assets/images/nile.svg", "assets/images/temple.svg", "assets/images/aswan.svg"],
    shortDescription: "A compact multi-day route connecting Egypt’s best temples along the Nile.",
    fullDescription:
      "Connect Luxor and Aswan with curated temple stops along the way. Built for travelers who want the highlights without complicated logistics. Great for couples and small groups seeking a smooth experience.",
    highlights: [
      "Temples and scenic stops along a classic Nile route",
      "Comfortable pacing with optimized drive times",
      "Local insights and photo opportunities",
      "Optional hotel and transport upgrades available later",
    ],
    included: ["Guide support", "Transport between stops"],
    excluded: ["Hotels", "Entry tickets", "Meals", "Gratuities"],
    itinerary: [
      { title: "Day 1 — Luxor departure", description: "Start and head toward major temple stops." },
      { title: "Day 1 — Scenic Nile views", description: "Photo breaks and storytelling." },
      { title: "Day 2 — Temple visits", description: "Continue with key sites and arrival in Aswan." },
      { title: "Day 2 — Drop-off", description: "End in Aswan at your hotel or selected point." },
    ],
    cancellation: "Free cancellation up to 48 hours before start time.",
    type: "Private",
    featured: true,
  },
  {
    id: "fts-008",
    title: "Luxor Sunrise Hot Air Balloon (Small Group, Early Start)",
    slug: "luxor-sunrise-hot-air-balloon-small-group",
    location: "Luxor",
    category: "Adventure",
    duration: { label: "2.5 hours", hours: 2.5, days: 0 },
    rating: 4.8,
    reviewsCount: 1597,
    price: 62,
    oldPrice: 75,
    badges: ["Top Rated", "Small Group", "Instant Confirmation"],
    image: "assets/images/balloon.svg",
    gallery: ["assets/images/balloon.svg", "assets/images/luxor.svg", "assets/images/nile.svg"],
    shortDescription: "Golden-hour views over temples, fields, and the Nile from above.",
    fullDescription:
      "Float above Luxor at sunrise for a once-in-a-lifetime view. This experience is built around a smooth early pickup, clear safety guidance, and a small-group vibe.",
    highlights: ["Sunrise flight with panoramic views", "Small-group experience", "Clear safety briefing and smooth logistics"],
    included: ["Pickup & drop-off (selected areas)", "Flight", "Safety briefing"],
    excluded: ["Gratuities", "Extra photo services"],
    itinerary: [
      { title: "Early pickup", description: "Transfer to launch site and safety briefing." },
      { title: "Sunrise flight", description: "Enjoy panoramic views and photo opportunities." },
      { title: "Return", description: "Smooth landing and drop-off." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
  {
    id: "fts-009",
    title: "Cairo: Egyptian Museum + Old Cairo Churches (Private Guide)",
    slug: "cairo-egyptian-museum-old-cairo-private-guide",
    location: "Cairo",
    category: "Museums",
    duration: { label: "7 hours", hours: 7, days: 0 },
    rating: 4.6,
    reviewsCount: 533,
    price: 58,
    badges: ["Private", "Free Cancellation"],
    image: "assets/images/museum.svg",
    gallery: ["assets/images/museum.svg", "assets/images/cairo.svg", "assets/images/oldcairo.svg"],
    shortDescription: "A deep dive into Egypt’s treasures plus the heritage of Old Cairo.",
    fullDescription:
      "Blend ancient artifacts with the layered history of Old Cairo. Your private guide adapts the pace based on interests—ideal for travelers who want depth without feeling rushed.",
    highlights: [
      "Highlights tour of the Egyptian Museum",
      "Old Cairo heritage churches and historic lanes",
      "Flexible pacing with a private licensed guide",
      "Practical tips for navigating Cairo with confidence",
    ],
    included: ["Private guide", "Transport"],
    excluded: ["Entry tickets", "Lunch", "Gratuities"],
    itinerary: [
      { title: "Pickup", description: "Meet your guide at your hotel." },
      { title: "Egyptian Museum", description: "Curated tour through key collections." },
      { title: "Old Cairo", description: "Heritage sites and walking stops." },
      { title: "Return", description: "Drop-off at your hotel." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Private",
    featured: false,
  },
  {
    id: "fts-010",
    title: "Aswan: Philae Temple Sound & Light Evening Experience",
    slug: "aswan-philae-temple-sound-and-light-evening",
    location: "Aswan",
    category: "Night Tours",
    duration: { label: "2.5 hours", hours: 2.5, days: 0 },
    rating: 4.3,
    reviewsCount: 214,
    price: 26,
    badges: ["Evening", "Instant Confirmation"],
    image: "assets/images/philae.svg",
    gallery: ["assets/images/philae.svg", "assets/images/aswan.svg", "assets/images/nights.svg"],
    shortDescription: "A magical nighttime visit with storytelling, lights, and island ambience.",
    fullDescription:
      "See Philae Temple transformed after dark. Enjoy a relaxing evening with a cinematic atmosphere and easy logistics that avoid the stress of arranging transport and tickets last minute.",
    highlights: ["Evening island ambience", "Storytelling and lights", "Easy logistics for a smooth night out"],
    included: ["Assistance with logistics", "Transfer support (where available)"],
    excluded: ["Tickets", "Food and drinks", "Gratuities"],
    itinerary: [
      { title: "Meet-up", description: "Meet and move toward the island transfer." },
      { title: "Show experience", description: "Enjoy the sound and light program." },
      { title: "Return", description: "Back to the meet-up point." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
  {
    id: "fts-011",
    title: "Hurghada: Private Speedboat to Orange Bay (Flexible Start)",
    slug: "hurghada-private-speedboat-orange-bay-flexible",
    location: "Hurghada",
    category: "Sea & Snorkeling",
    duration: { label: "5 hours", hours: 5, days: 0 },
    rating: 4.9,
    reviewsCount: 301,
    price: 180,
    badges: ["Top Rated", "Private", "Free Cancellation"],
    image: "assets/images/orangebay.svg",
    gallery: ["assets/images/orangebay.svg", "assets/images/reef.svg", "assets/images/island.svg"],
    shortDescription: "Premium private boat time with curated snorkeling and a beach stop.",
    fullDescription:
      "Upgrade to a private speedboat for a flexible start time and a tailored route. Great for families, couples, and groups who want a more exclusive Red Sea day.",
    highlights: ["Private boat with flexible start", "Snorkeling stops picked for conditions", "Orange Bay beach time"],
    included: ["Private boat", "Captain/crew", "Snorkel gear"],
    excluded: ["Transfers", "Food and drinks", "Gratuities"],
    itinerary: [
      { title: "Marina meet-up", description: "Quick briefing and departure." },
      { title: "Snorkel stops", description: "2–3 stops depending on conditions." },
      { title: "Orange Bay", description: "Beach stop and relaxation." },
      { title: "Return", description: "Back to the marina." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Private",
    featured: true,
  },
  {
    id: "fts-012",
    title: "Sharm: Ras Mohammed National Park Snorkel Day (Reefs + Lunch)",
    slug: "sharm-ras-mohammed-national-park-snorkel-day",
    location: "Sharm El Sheikh",
    category: "Sea & Snorkeling",
    duration: { label: "7 hours", hours: 7, days: 0 },
    rating: 4.6,
    reviewsCount: 904,
    price: 44,
    badges: ["Best Seller", "Lunch Included", "Free Cancellation"],
    image: "assets/images/rasmohammed.svg",
    gallery: ["assets/images/rasmohammed.svg", "assets/images/reef.svg", "assets/images/sharm.svg"],
    shortDescription: "A reef-packed day in one of the Red Sea’s most iconic marine reserves.",
    fullDescription:
      "Enjoy a full-day snorkel experience with stunning reef sites and relaxed breaks. Perfect for travelers who want an easy, guided day with lunch included and clear safety guidance.",
    highlights: ["Reef snorkeling in a famous marine reserve", "Lunch included", "Beginner-friendly support and briefing"],
    included: ["Guide support", "Lunch", "Snorkel gear (where available)"],
    excluded: ["Transfers (optional)", "Gratuities", "Diving add-ons"],
    itinerary: [
      { title: "Pickup/meet-up", description: "Start with safety briefing and route overview." },
      { title: "Reef sites", description: "Multiple snorkel stops depending on conditions." },
      { title: "Lunch", description: "Lunch break and rest time." },
      { title: "Return", description: "Back to Sharm." },
    ],
    cancellation: "Free cancellation up to 24 hours before start time.",
    type: "Group",
    featured: false,
  },
];

export const popularDestinations = ["Cairo", "Hurghada", "Luxor", "Aswan", "Sharm El Sheikh"];

export const categories = [
  "Historical",
  "Culture & Food",
  "Sea & Snorkeling",
  "Adventure",
  "Museums",
  "Night Tours",
  "Multi-day",
];

export function getTourBySlug(slug) {
  return tours.find((t) => t.slug === slug) || null;
}

export function getRelatedTours(slug, limit = 4) {
  const current = getTourBySlug(slug);
  if (!current) return tours.slice(0, limit);

  const sameLocation = tours.filter((t) => t.slug !== slug && t.location === current.location);
  const sameCategory = tours.filter((t) => t.slug !== slug && t.category === current.category);

  const combined = [...sameLocation, ...sameCategory].reduce((acc, t) => {
    if (!acc.some((x) => x.slug === t.slug)) acc.push(t);
    return acc;
  }, []);

  return combined.slice(0, limit);
}

